### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by zmkuu** [imgag/megSAP#17]
We just tried to istall megSAP.

everyting went smooth until:
./download_tools.sh
Resulted in some problems (see attached file)

./download_GRCh37.sh
also terminated with an error (see attaced file)

What might be the problem?

[download_tools.sh_output.txt](https://github.com/imgag/megSAP/files/2325029/download_tools.sh_output.txt)
[download_GRCh37.sh_output.txt](https://github.com/imgag/megSAP/files/2325030/download_GRCh37.sh_output.txt)

**Comment by marc-sturm** [comment]
Hi,

The tools installation fails because libGL is missing. Please try to
install OpenGL or some other package that contains the libGL.so.

The genome download fails because the tools installation is not complete
(BWA is not yet installed).

I am on vacation with really bad Internet connection, so my replies will be
slow.

Best, Marc

zmkuu <notifications@github.com> schrieb am Mo., 27. Aug. 2018, 20:02:

**Comment by zmkuu** [comment]
Hi Marc, 
thank you so much. 
I went through hell to install this library. Mainly because I use my server through ssh and there is no monitor attached to it. Somehow installing OpenGL and trying to fix issues resulted in a boot loop and other really messy problems.
But I did it! 
Installation should have worked fine.
I am still running sownload_dbs.sh
Thanks again.
Alex
