### ISSUE TITLE
Update precalcualted SpliceAI scores

### ISSUE THREAD

**Issue by marc-sturm** [imgag/megSAP#222]
ToDo:
- [x] update precalculated scores (use masked scores)

Note:
the plan was to increase D to 300 to score larger indels. This is not feasable due to the increased compute time

**Comment by alex-seitz** [comment]
Hey,
I just saw this issue and wanted to comment on it, because a biologist told us, that the "wrong" spliceai-scores seem to be annoteted.
There are two versions "masked" and "raw". For diagnostic purposes the "masked" score should apprarently be used, whereas the "raw" score seems to be annotated. (See question mark next to Score type here: https://spliceailookup.broadinstitute.org/)
It is not really a priority, but because I just saw this issue, I thought I let you know

**Comment by marc-sturm** [comment]
Hi Alex,

yes, some variants may get a too high score because the effect is overestimated when using mask=0.
I will have to check how long it takes to re-calculate all scores with mask=1...

Best,
  Marc

**Comment by marc-sturm** [comment]
Changed pipeline to use masked scores:
https://github.com/imgag/megSAP/commit/628bbf4b4c1c8583687d695447b85d03a77baba8

**Comment by marc-sturm** [comment]
Updated precalculated scores:
56c1452e69f2d453f044d8eaad46bd283d34f04d
