### ISSUE TITLE
variants missed by strelka

### ISSUE THREAD

**Issue by marc-sturm** [imgag/megSAP#62]
Check how we can find missing variants:
- variants from Sorins email

Validate new criteria in spike-in data from somatic validation

**Comment by axelgschwind** [comment]
We should not change Strelka2 parameters and we should keep removing variants not flagged with "PASS" by strelka.

Instead, we post filter the variants that were removed (because they don't have PASS flag) by the following criteria:
freq-tum, freq-nor < 20
min_af in tumor > 0.5%

somaticEVS > 5
MQ > 30
SNVSB > 0.05

These variants are then flagged as STRELKA_LOW_QUAL and then added to the conventional variant list.

**Comment by axelgschwind** [comment]
After reviewing for
DX204631   chr3:178936094
DX205138   chr7:55249058

the parameters were set to
freq-tum, freq-nor < 20
min_af in tumor > 0.45%
somaticEVS > 4
MQ > 30
SNVSB > 0.05

in vc_strelka2.php and flagged in filter column with LowEVS for the user.
